### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by lloydmeta** [kailuowang/mainecoon#15]
Hi there,

Just stumbled onto this project. It looks like you and I independently ended up in pretty much the same space. If you haven't yet, take a look at [diesel](https://github.com/lloydmeta/diesel).

Maybe we can work together?

Lloyd

**Comment by kailuowang** [comment]
@lloydmeta diesel looks cool. You are right we came in to solve the exact same problem with similar approaches. It would be great to work together. How would you like to collaborate?

**Comment by kailuowang** [comment]
Still interested in this?  Since I didn't hear from you, I'm closing it for now but feel free to re-open if you want to continue the conversation. Cheers.

**Comment by lloydmeta** [comment]
Oops, completely lost track of this. Yeah, I'm still interested, but am not entirely sure how to proceed with collaboration: it looks like mainecoon has by now has gained a lot more functionality over diesel. You've also done a great job with documentation :)

From what I can tell, the only trick that diesel has that mainecoon does not is aliasing an in-scope interpreter to the companion object; if it's something you'd like to add, lemme know. The other thing is that diesel doesn't depend on cats, but given that mainecoon set out to be a typelevel project, it's understandable.

**Comment by kailuowang** [comment]
@lloydmeta I thought about that, then I realized that aliasing methods might be hard if you want to consider extra type parameters or abstract type members on the algebras. I added an easy instance summon apply method to the companion object so that users can do `MyAlgebra[F].foo(bar)` if they want. Another alternative is to import all the methods directly from the interpreter.
