### ISSUE TITLE
Suppress wartremover warnings

### ISSUE THREAD

**Issue by nigredo-tori** [kailuowang/mainecoon#24]
There is a relatively popular linter for Scala - wartremover. It works as a compiler plugin, which allows it to tap into typing and other low-level compiler details to provide some pretty useful checks ("warts"). The problem is that it has to work after macro expansion phase. As far as I understand, there is no reliable way to detect expanded macros, though.

This means that mainecoon's generated code gets checked as well. In particular, this sample:
```scala
@autoFunctorK
trait Foo[F[_]] {
  def pure[A](a: A): F[A]
}
```
triggers this warning:
```scala
<macro>:9: [wartremover:ImplicitParameter] Implicit parameters are disabled
      object autoDerive { implicit def fromFunctorK[F[_], G[_]](implicit fk: _root_.cats.~>[F, G], FK: _root_.mainecoon.FunctorK[({ type λ[Ƒ[_]] = Foo[Ƒ] })#λ], af: Foo[F]): Foo[G] = FK.mapK(af)(fk) }
                                       ^
```
The root of the issue here seems to be implicit parameter `FK`, which includes neither `F`, nor `G`.

Here are the ways for a user to get rid of this warning:
1. Disable this wart for the whole project
2. Exclude all files using `autoFunctorK`
3. Add `@SuppressWarnings` annotation to the companion object

The third approach, though a bit counterintuitive, allows at least some granularity.

It would be far better to only exclude the generated code. This, however, can only be done in mainecoon itself. This would only require adding this annotation to generated definitions:
```scala
@SuppressWarnings(Array("org.wartremover.warts.ImplicitParameter"))
```

**Comment by kailuowang** [comment]
Sorry for the late reply. I wouldn't be against adding it to the generated definitions (one in `autoFunctorK` and one in `autoInvariantK`. So a PR is more than welcome. Another option for you is that if you don't need auto derivation,  you can disable it so that such code won't be generated, after all, it IS an implicit parameter. So if it doesn't go well with your taste and you don't need this functionality, turning it off might be better.   `@autoFunctorK(autoDerivation = false)`
